Repository laminas/laminas-httphandlerrunner, pull requests merged in 2021-07, with the labels that each got.

#12 qa: remove changelog file
  CHANGELOG.md
Labels: Enhancement

#9 Remove dependency on laminas/laminas-zendframework-bridge
  composer.json
Labels: BC Break

#16 feature: introduce `RequestHandlerRunnerInterface`
  src/RequestHandlerRunner.php
  src/RequestHandlerRunnerInterface.php
Labels: BC Break, Enhancement

#15 feature: hardening type-safety
  psalm-baseline.xml
  psalm.xml.dist
  src/Emitter/EmitterStack.php
  src/Emitter/SapiEmitterTrait.php
  src/Emitter/SapiStreamEmitter.php
  src/RequestHandlerRunner.php
  test/ConfigProviderTest.php
  test/Emitter/AbstractEmitterTest.php
  test/Emitter/EmitterStackTest.php
  test/Emitter/SapiStreamEmitterTest.php
  test/RequestHandlerRunnerTest.php
  test/TestAsset/HeaderStack.php
  test/TestAsset/MockStreamHelper.php
  test/TestAsset/SapiResponse.php
Labels: BC Break, Enhancement

#14 Coding Standard v2
  .gitignore
  composer.json
  composer.lock
  phpcs.xml
  src/ConfigProvider.php
  src/Emitter/EmitterInterface.php
  src/Emitter/EmitterStack.php
  src/Emitter/SapiEmitter.php
  src/Emitter/SapiEmitterTrait.php
  src/Emitter/SapiStreamEmitter.php
  src/Exception/EmitterException.php
  src/Exception/ExceptionInterface.php
  src/Exception/InvalidEmitterException.php
  src/RequestHandlerRunner.php
  src/RequestHandlerRunnerInterface.php
  test/ConfigProviderTest.php
  test/Emitter/AbstractEmitterTest.php
  test/Emitter/EmitterStackTest.php
  test/Emitter/SapiEmitterTest.php
  test/Emitter/SapiStreamEmitterTest.php
  test/RequestHandlerRunnerTest.php
  test/TestAsset/HeaderStack.php
  test/TestAsset/MockStreamHelper.php
  test/TestAsset/SapiResponse.php
Labels: BC Break, Enhancement

#17 feature: Add additional `headers_sent` informations to the `EmitterException`
  composer.json
  composer.lock
  src/Emitter/SapiEmitterTrait.php
  src/Exception/EmitterException.php
  test/Emitter/AbstractEmitterTest.php
  test/TestAsset/HeadersSent.php
  test/TestAsset/SapiResponse.php
Labels: Enhancement

#18 qa: remove leftover file headers
  test/Emitter/EmitterStackTest.php
  test/Emitter/SapiEmitterTest.php
  test/TestAsset/MockStreamHelper.php
Labels: Enhancement

#19 qa: synchronize lock file
  composer.lock
Labels: Bug
